"""Inventory schemas package."""

from modules.inventory.schemas.base import (
    FeatureFlagResponse,
    FeatureFlagUpdateRequest,
    InventoryBaseSchema,
    PaginatedResponse,
)
from modules.inventory.schemas.master_data import (
    AttributeDefinitionCreateRequest,
    AttributeDefinitionResponse,
    AttributeDefinitionUpdateRequest,
    AttributeSetCreateRequest,
    AttributeSetMembershipAddRequest,
    AttributeSetMembershipResponse,
    AttributeSetResponse,
    BrandCreateRequest,
    BrandResponse,
    BrandUpdateRequest,
    CategoryCreateRequest,
    CategoryResponse,
    CategoryUpdateRequest,
    CustomFieldCreateRequest,
    CustomFieldResponse,
    CustomFieldUpdateRequest,
    ReasonCodeCreateRequest,
    ReasonCodeResponse,
    ReasonCodeUpdateRequest,
    TagCreateRequest,
    TagResponse,
    TagUpdateRequest,
    UOMConversionCreateRequest,
    UOMConversionResponse,
    UOMCreateRequest,
    UOMResponse,
    UOMUpdateRequest,
)

__all__ = [
    # base
    "FeatureFlagResponse",
    "FeatureFlagUpdateRequest",
    "InventoryBaseSchema",
    "PaginatedResponse",
    # master data
    "AttributeDefinitionCreateRequest",
    "AttributeDefinitionResponse",
    "AttributeDefinitionUpdateRequest",
    "AttributeSetCreateRequest",
    "AttributeSetMembershipAddRequest",
    "AttributeSetMembershipResponse",
    "AttributeSetResponse",
    "BrandCreateRequest",
    "BrandResponse",
    "BrandUpdateRequest",
    "CategoryCreateRequest",
    "CategoryResponse",
    "CategoryUpdateRequest",
    "CustomFieldCreateRequest",
    "CustomFieldResponse",
    "CustomFieldUpdateRequest",
    "ReasonCodeCreateRequest",
    "ReasonCodeResponse",
    "ReasonCodeUpdateRequest",
    "TagCreateRequest",
    "TagResponse",
    "TagUpdateRequest",
    "UOMConversionCreateRequest",
    "UOMConversionResponse",
    "UOMCreateRequest",
    "UOMResponse",
    "UOMUpdateRequest",
]
